--CREATE USER
CREATE TABLESPACE DEMO DATAFILE '/opt/oracle/oradata/XE/XEPDB1/DEMO.DBF' SIZE 10M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO;
CREATE USER DEMO IDENTIFIED BY ******** DEFAULT TABLESPACE DEMO TEMPORARY TABLESPACE TEMP;
ALTER USER DEMO quota unlimited on DEMO;

--ACCESS PRIVILEGES
GRANT CREATE SESSION TO DEMO;

--CREATE TABLES
CREATE TABLE USERS(
	PK VARCHAR(4000) PRIMARY KEY NOT NULL,
	EMAIL VARCHAR(4000) NOT NULL,
	PASSWORD VARCHAR(4000) NOT NULL,
	NAME VARCHAR(4000),
	TOKEN VARCHAR(4000) NOT NULL,
	CREATION_DATE DATE DEFAULT SYSDATE,
	DISABLED NUMBER DEFAULT 0
);
